# Site settings
title: Padley Family
email: nick@nickpadley.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  #
url:  http://padley.github.io/
twitter_username: nickpadley,'CNAME'
github_username:  npadley

# Plugins 
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

prose:
  ignore: ['_config.yml','.gitignore','/_includes','_layouts','_sass','Gemfile','Gemfile.lock','CNAME']
  siteurl: 'http://padley.gihub.io/'
  media: 'img'
  metadata:
    _portfolio:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
      - name: "img"
        field:
          element: "text"
          label: "Linking Image"
          value: ""
      - name: "redirect"
        field:
          element: "text"
          label: "URL to Redirect"
          value: ""
